services:
  - type: web
    name: aimlbudgettracker-backend
    env: python
    plan: free                      # or starter, standard depending on your needs
    region: oregon                  # choose the closest region for your users
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000