"""Add date column to expenses

Revision ID: 018dee2ea836
Revises: 786613d52627
Create Date: 2025-09-16 12:56:22.012713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018dee2ea836'
down_revision = '786613d52627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('date')

    # ### end Alembic commands ###
